### ISSUE TITLE
onScroll listener is not a valid function

### ISSUE THREAD

**Issue by petegore** [wangpin34/vue-scroll#6]
Hi there,

I got this error when using the scroll event vith vue 2.0

> vue.js:1739 Uncaught (in promise) Error: onScroll listener is not a valid function(…)

Here is my HTML : 

```html
<div id="boards-list" v-scroll="onScroll">
    <!-- App Code -->
</div>
```

And here is my Vue : 

```js
Vue = require('vue');
var VueScroll = require('vue-scroll');
Vue.use(VueScroll);

BoardsList = new Vue({
    el: "#boards-list",
    // .....
    methods: {
        onScroll: function(e, position) {
            alert("Hi there !");
        },
        //...
     },
}
```

The part of the vue-scroll files throwing the error is this one : 

```js
Vue.directive('scroll', {
        bind: function () {
          console.log('prepare for bind vue-scroll on specify dom');
        },
        update: function (newListener, oldListener) {
          //replace old listener by new listener
          var self = this,
             el = this.el;
          if(!newListener || typeof newListener !== 'function'){
            throw new Error('onScroll listener is not a valid function');
          }
```

I don't see any mistake in my code.
Any help ?

Thanks :)

**Comment by wangpin34** [comment]
@petegore Thanks for your quite detailed report about the issue. Actually your code is right but it  is unfortunate that the published latest vue-scroll@v1.0.4 doesn't support vue 2.0. And you know there are lots of differences about build a customer directive like vue-scroll. So the error happened at your side.

I have began to create a [new branch](https://github.com/wangpin34/vue-scroll/tree/2.0-compatible) for vue 2.0 because it's a little bit complicated that support both vue 1.x and 2.0. And the first version was published.

**Comment by wangpin34** [comment]
Close this bug due to vue-scroll 2.0.0 is published to support vue 2.0.

**Comment by petegore** [comment]
Thanks ! :)

**Comment by petegore** [comment]
Just a question : to handle scroll on the whole page, do I have to define the app on the body element ?

**Comment by wangpin34** [comment]
@petegore Yes. You have to.
